# Use an OpenJDK base image
FROM openjdk:17-alpine

# Set the working directory inside the container
WORKDIR /Weddify2/emailapp

# Copy the Spring Boot application JAR file into the container
COPY . .

# Specify the command to run the application when the container starts
# CMD ["java", "-jar", "emailapp.jar"]
