# Generated by Django 3.2.14 on 2023-07-06 09:47

import datetime
from django.db import migrations, models
import orders.storage_backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('end_date', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('service_id', models.IntegerField(default=1)),
                ('vendor_id', models.IntegerField(default=1)),
                ('user_id', models.IntegerField(default=1)),
                ('amount', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'PENDING')], default=3)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('order_id', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('receiptpdf', models.FileField(storage=orders.storage_backend.PrivateMediaStorage(), upload_to='')),
            ],
        ),
    ]
