# Generated by Django 3.2.14 on 2023-07-06 03:22

import ckeditor.fields
import datetime
from django.db import migrations, models
import services.storage_backend


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('Photographer', 'Photographer'), ('Venue', 'Venue'), ('Caterer', 'Caterer'), ('Bridal Services', 'Bridal Services')], max_length=100)),
                ('vendor_id', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhattisgarh', 'Chhattisgarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Lakshadweep', 'Lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Puducherry', 'Puducherry'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=100)),
                ('featured_package_price', models.IntegerField()),
                ('service_photo_0', models.FileField(storage=services.storage_backend.PublicMediaStorage(), upload_to='')),
                ('service_photo_1', models.FileField(blank=True, storage=services.storage_backend.PublicMediaStorage(), upload_to='')),
                ('service_photo_2', models.FileField(blank=True, storage=services.storage_backend.PublicMediaStorage(), upload_to='')),
                ('service_photo_3', models.FileField(blank=True, storage=services.storage_backend.PublicMediaStorage(), upload_to='')),
                ('service_photo_4', models.FileField(blank=True, storage=services.storage_backend.PublicMediaStorage(), upload_to='')),
                ('description', ckeditor.fields.RichTextField()),
                ('other_details', ckeditor.fields.RichTextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
